/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteImport } from './routes/post'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DemoLayoutRouteImport } from './routes/_demoLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as DotDotPagesFeaturesIndexRouteImport } from './pages/features/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as DotDotPagesFeaturesFeatureIdRouteImport } from './pages/features/$featureId'
import { Route as PostDotpostIdRouteImport } from './routes/post.$postId'
import { Route as DemoLayoutDotdemoRouteImport } from './routes/_demoLayout.demo'
import { Route as PostDotpostIdDotmodelRouteImport } from './routes/post.$postId.model'

const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutRoute = DemoLayoutRouteImport.update({
  id: '/_demoLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotPagesFeaturesIndexRoute =
  DotDotPagesFeaturesIndexRouteImport.update({
    id: '/shops/',
    path: '/shops/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotPagesFeaturesFeatureIdRoute =
  DotDotPagesFeaturesFeatureIdRouteImport.update({
    id: '/shops/$featureId',
    path: '/shops/$featureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostDotpostIdRoute = PostDotpostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostRoute,
} as any)
const DemoLayoutDotdemoRoute = DemoLayoutDotdemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => DemoLayoutRoute,
} as any)
const PostDotpostIdDotmodelRoute = PostDotpostIdDotmodelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => PostDotpostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/post': typeof PostRouteWithChildren
  '/demo': typeof DemoLayoutDotdemoRoute
  '/post/$postId': typeof PostDotpostIdRouteWithChildren
  '/shops/$featureId': typeof DotDotPagesFeaturesFeatureIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/shops/': typeof DotDotPagesFeaturesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/post/$postId/model': typeof PostDotpostIdDotmodelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/post': typeof PostRouteWithChildren
  '/demo': typeof DemoLayoutDotdemoRoute
  '/post/$postId': typeof PostDotpostIdRouteWithChildren
  '/shops/$featureId': typeof DotDotPagesFeaturesFeatureIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/shops': typeof DotDotPagesFeaturesIndexRoute
  '/users': typeof UsersIndexRoute
  '/post/$postId/model': typeof PostDotpostIdDotmodelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_demoLayout': typeof DemoLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/post': typeof PostRouteWithChildren
  '/_demoLayout/demo': typeof DemoLayoutDotdemoRoute
  '/post/$postId': typeof PostDotpostIdRouteWithChildren
  '/shops/$featureId': typeof DotDotPagesFeaturesFeatureIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/shops/': typeof DotDotPagesFeaturesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/post/$postId/model': typeof PostDotpostIdDotmodelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/post'
    | '/demo'
    | '/post/$postId'
    | '/shops/$featureId'
    | '/users/$userId'
    | '/shops/'
    | '/users/'
    | '/post/$postId/model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/post'
    | '/demo'
    | '/post/$postId'
    | '/shops/$featureId'
    | '/users/$userId'
    | '/shops'
    | '/users'
    | '/post/$postId/model'
  id:
    | '__root__'
    | '/'
    | '/_demoLayout'
    | '/about'
    | '/post'
    | '/_demoLayout/demo'
    | '/post/$postId'
    | '/shops/$featureId'
    | '/users/$userId'
    | '/shops/'
    | '/users/'
    | '/post/$postId/model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoLayoutRoute: typeof DemoLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  PostRoute: typeof PostRouteWithChildren
  DotDotPagesFeaturesFeatureIdRoute: typeof DotDotPagesFeaturesFeatureIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  DotDotPagesFeaturesIndexRoute: typeof DotDotPagesFeaturesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demoLayout': {
      id: '/_demoLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DemoLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof DotDotPagesFeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$featureId': {
      id: '/shops/$featureId'
      path: '/shops/$featureId'
      fullPath: '/shops/$featureId'
      preLoaderRoute: typeof DotDotPagesFeaturesFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostDotpostIdRouteImport
      parentRoute: typeof PostRoute
    }
    '/_demoLayout/demo': {
      id: '/_demoLayout/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoLayoutDotdemoRouteImport
      parentRoute: typeof DemoLayoutRoute
    }
    '/post/$postId/model': {
      id: '/post/$postId/model'
      path: '/model'
      fullPath: '/post/$postId/model'
      preLoaderRoute: typeof PostDotpostIdDotmodelRouteImport
      parentRoute: typeof PostDotpostIdRoute
    }
  }
}

interface DemoLayoutRouteChildren {
  DemoLayoutDotdemoRoute: typeof DemoLayoutDotdemoRoute
}

const DemoLayoutRouteChildren: DemoLayoutRouteChildren = {
  DemoLayoutDotdemoRoute: DemoLayoutDotdemoRoute,
}

const DemoLayoutRouteWithChildren = DemoLayoutRoute._addFileChildren(
  DemoLayoutRouteChildren,
)

interface PostDotpostIdRouteChildren {
  PostDotpostIdDotmodelRoute: typeof PostDotpostIdDotmodelRoute
}

const PostDotpostIdRouteChildren: PostDotpostIdRouteChildren = {
  PostDotpostIdDotmodelRoute: PostDotpostIdDotmodelRoute,
}

const PostDotpostIdRouteWithChildren = PostDotpostIdRoute._addFileChildren(
  PostDotpostIdRouteChildren,
)

interface PostRouteChildren {
  PostDotpostIdRoute: typeof PostDotpostIdRouteWithChildren
}

const PostRouteChildren: PostRouteChildren = {
  PostDotpostIdRoute: PostDotpostIdRouteWithChildren,
}

const PostRouteWithChildren = PostRoute._addFileChildren(PostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoLayoutRoute: DemoLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  PostRoute: PostRouteWithChildren,
  DotDotPagesFeaturesFeatureIdRoute: DotDotPagesFeaturesFeatureIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  DotDotPagesFeaturesIndexRoute: DotDotPagesFeaturesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
