/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteImport } from './routes/post'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DemoLayoutRouteImport } from './routes/_demoLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ProductsIndexRouteImport } from './pages/productss/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ProductsProductIdRouteImport } from './pages/productss/$productId'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as DemoLayoutDemoRouteImport } from './routes/_demoLayout.demo'
import { Route as PostPostIdModelRouteImport } from './routes/post.$postId.model'

const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutRoute = DemoLayoutRouteImport.update({
  id: '/_demoLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostRoute,
} as any)
const DemoLayoutDemoRoute = DemoLayoutDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => DemoLayoutRoute,
} as any)
const PostPostIdModelRoute = PostPostIdModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => PostPostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/post': typeof PostRouteWithChildren
  '/demo': typeof DemoLayoutDemoRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/products/': typeof ProductsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/post/$postId/model': typeof PostPostIdModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/post': typeof PostRouteWithChildren
  '/demo': typeof DemoLayoutDemoRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/products': typeof ProductsIndexRoute
  '/users': typeof UsersIndexRoute
  '/post/$postId/model': typeof PostPostIdModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_demoLayout': typeof DemoLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/post': typeof PostRouteWithChildren
  '/_demoLayout/demo': typeof DemoLayoutDemoRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/products/': typeof ProductsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/post/$postId/model': typeof PostPostIdModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/post'
    | '/demo'
    | '/post/$postId'
    | '/products/$productId'
    | '/users/$userId'
    | '/products/'
    | '/users/'
    | '/post/$postId/model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/post'
    | '/demo'
    | '/post/$postId'
    | '/products/$productId'
    | '/users/$userId'
    | '/products'
    | '/users'
    | '/post/$postId/model'
  id:
    | '__root__'
    | '/'
    | '/_demoLayout'
    | '/about'
    | '/post'
    | '/_demoLayout/demo'
    | '/post/$postId'
    | '/products/$productId'
    | '/users/$userId'
    | '/products/'
    | '/users/'
    | '/post/$postId/model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoLayoutRoute: typeof DemoLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  PostRoute: typeof PostRouteWithChildren
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demoLayout': {
      id: '/_demoLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DemoLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof PostRoute
    }
    '/_demoLayout/demo': {
      id: '/_demoLayout/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoLayoutDemoRouteImport
      parentRoute: typeof DemoLayoutRoute
    }
    '/post/$postId/model': {
      id: '/post/$postId/model'
      path: '/model'
      fullPath: '/post/$postId/model'
      preLoaderRoute: typeof PostPostIdModelRouteImport
      parentRoute: typeof PostPostIdRoute
    }
  }
}

interface DemoLayoutRouteChildren {
  DemoLayoutDemoRoute: typeof DemoLayoutDemoRoute
}

const DemoLayoutRouteChildren: DemoLayoutRouteChildren = {
  DemoLayoutDemoRoute: DemoLayoutDemoRoute,
}

const DemoLayoutRouteWithChildren = DemoLayoutRoute._addFileChildren(
  DemoLayoutRouteChildren,
)

interface PostPostIdRouteChildren {
  PostPostIdModelRoute: typeof PostPostIdModelRoute
}

const PostPostIdRouteChildren: PostPostIdRouteChildren = {
  PostPostIdModelRoute: PostPostIdModelRoute,
}

const PostPostIdRouteWithChildren = PostPostIdRoute._addFileChildren(
  PostPostIdRouteChildren,
)

interface PostRouteChildren {
  PostPostIdRoute: typeof PostPostIdRouteWithChildren
}

const PostRouteChildren: PostRouteChildren = {
  PostPostIdRoute: PostPostIdRouteWithChildren,
}

const PostRouteWithChildren = PostRoute._addFileChildren(PostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoLayoutRoute: DemoLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  PostRoute: PostRouteWithChildren,
  ProductsProductIdRoute: ProductsProductIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
